api_platform:
    title: Ultima API
    version: 0.0.2
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    docs_formats:
        html: ['text/html']
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
